// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: dkvs/balancer/commands.proto

package prototypes

import (
	prototypes "github.com/pysel/dkvs/prototypes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *prototypes.StoreMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *StoreMessageRequest) Reset() {
	*x = StoreMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_balancer_commands_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMessageRequest) ProtoMessage() {}

func (x *StoreMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_balancer_commands_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMessageRequest.ProtoReflect.Descriptor instead.
func (*StoreMessageRequest) Descriptor() ([]byte, []int) {
	return file_dkvs_balancer_commands_proto_rawDescGZIP(), []int{0}
}

func (x *StoreMessageRequest) GetMessage() *prototypes.StoreMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

type StoreMessageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StoreMessageResponse) Reset() {
	*x = StoreMessageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_balancer_commands_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMessageResponse) ProtoMessage() {}

func (x *StoreMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_balancer_commands_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMessageResponse.ProtoReflect.Descriptor instead.
func (*StoreMessageResponse) Descriptor() ([]byte, []int) {
	return file_dkvs_balancer_commands_proto_rawDescGZIP(), []int{1}
}

var File_dkvs_balancer_commands_proto protoreflect.FileDescriptor

var file_dkvs_balancer_commands_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x64, 0x6b, 0x76, 0x73, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d,
	0x64, 0x6b, 0x76, 0x73, 0x2e, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x1a, 0x1a, 0x64,
	0x6b, 0x76, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4b, 0x0a, 0x13, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x34, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6a,
	0x0a, 0x0f, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x57, 0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x22, 0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x64, 0x6b, 0x76, 0x73, 0x2e, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x79, 0x73, 0x65, 0x6c, 0x2f, 0x64,
	0x6b, 0x76, 0x73, 0x2f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dkvs_balancer_commands_proto_rawDescOnce sync.Once
	file_dkvs_balancer_commands_proto_rawDescData = file_dkvs_balancer_commands_proto_rawDesc
)

func file_dkvs_balancer_commands_proto_rawDescGZIP() []byte {
	file_dkvs_balancer_commands_proto_rawDescOnce.Do(func() {
		file_dkvs_balancer_commands_proto_rawDescData = protoimpl.X.CompressGZIP(file_dkvs_balancer_commands_proto_rawDescData)
	})
	return file_dkvs_balancer_commands_proto_rawDescData
}

var file_dkvs_balancer_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dkvs_balancer_commands_proto_goTypes = []interface{}{
	(*StoreMessageRequest)(nil),     // 0: dkvs.balancer.StoreMessageRequest
	(*StoreMessageResponse)(nil),    // 1: dkvs.balancer.StoreMessageResponse
	(*prototypes.StoreMessage)(nil), // 2: dkvs.message.StoreMessage
}
var file_dkvs_balancer_commands_proto_depIdxs = []int32{
	2, // 0: dkvs.balancer.StoreMessageRequest.message:type_name -> dkvs.message.StoreMessage
	0, // 1: dkvs.balancer.CommandsService.StoreMessage:input_type -> dkvs.balancer.StoreMessageRequest
	1, // 2: dkvs.balancer.CommandsService.StoreMessage:output_type -> dkvs.balancer.StoreMessageResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dkvs_balancer_commands_proto_init() }
func file_dkvs_balancer_commands_proto_init() {
	if File_dkvs_balancer_commands_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dkvs_balancer_commands_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dkvs_balancer_commands_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreMessageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dkvs_balancer_commands_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dkvs_balancer_commands_proto_goTypes,
		DependencyIndexes: file_dkvs_balancer_commands_proto_depIdxs,
		MessageInfos:      file_dkvs_balancer_commands_proto_msgTypes,
	}.Build()
	File_dkvs_balancer_commands_proto = out.File
	file_dkvs_balancer_commands_proto_rawDesc = nil
	file_dkvs_balancer_commands_proto_goTypes = nil
	file_dkvs_balancer_commands_proto_depIdxs = nil
}
