// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: dkvs/partition/rpc.proto

package partition

import (
	context "context"
	prototypes "github.com/pysel/dkvs/prototypes"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PartitionServiceClient is the client API for PartitionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartitionServiceClient interface {
	SetMessage(ctx context.Context, in *prototypes.SetMessageRequest, opts ...grpc.CallOption) (*prototypes.SetMessageResponse, error)
	GetMessage(ctx context.Context, in *prototypes.GetMessageRequest, opts ...grpc.CallOption) (*prototypes.GetMessageResponse, error)
	DeleteMessage(ctx context.Context, in *prototypes.DeleteMessageRequest, opts ...grpc.CallOption) (*prototypes.DeleteMessageResponse, error)
	// SetHashrange sets this node's hashrange to the given range.
	SetHashrange(ctx context.Context, in *prototypes.SetHashrangeRequest, opts ...grpc.CallOption) (*prototypes.SetHashrangeResponse, error)
}

type partitionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartitionServiceClient(cc grpc.ClientConnInterface) PartitionServiceClient {
	return &partitionServiceClient{cc}
}

func (c *partitionServiceClient) SetMessage(ctx context.Context, in *prototypes.SetMessageRequest, opts ...grpc.CallOption) (*prototypes.SetMessageResponse, error) {
	out := new(prototypes.SetMessageResponse)
	err := c.cc.Invoke(ctx, "/dkvs.partition.PartitionService/SetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionServiceClient) GetMessage(ctx context.Context, in *prototypes.GetMessageRequest, opts ...grpc.CallOption) (*prototypes.GetMessageResponse, error) {
	out := new(prototypes.GetMessageResponse)
	err := c.cc.Invoke(ctx, "/dkvs.partition.PartitionService/GetMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionServiceClient) DeleteMessage(ctx context.Context, in *prototypes.DeleteMessageRequest, opts ...grpc.CallOption) (*prototypes.DeleteMessageResponse, error) {
	out := new(prototypes.DeleteMessageResponse)
	err := c.cc.Invoke(ctx, "/dkvs.partition.PartitionService/DeleteMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partitionServiceClient) SetHashrange(ctx context.Context, in *prototypes.SetHashrangeRequest, opts ...grpc.CallOption) (*prototypes.SetHashrangeResponse, error) {
	out := new(prototypes.SetHashrangeResponse)
	err := c.cc.Invoke(ctx, "/dkvs.partition.PartitionService/SetHashrange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartitionServiceServer is the server API for PartitionService service.
// All implementations must embed UnimplementedPartitionServiceServer
// for forward compatibility
type PartitionServiceServer interface {
	SetMessage(context.Context, *prototypes.SetMessageRequest) (*prototypes.SetMessageResponse, error)
	GetMessage(context.Context, *prototypes.GetMessageRequest) (*prototypes.GetMessageResponse, error)
	DeleteMessage(context.Context, *prototypes.DeleteMessageRequest) (*prototypes.DeleteMessageResponse, error)
	// SetHashrange sets this node's hashrange to the given range.
	SetHashrange(context.Context, *prototypes.SetHashrangeRequest) (*prototypes.SetHashrangeResponse, error)
	mustEmbedUnimplementedPartitionServiceServer()
}

// UnimplementedPartitionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPartitionServiceServer struct {
}

func (UnimplementedPartitionServiceServer) SetMessage(context.Context, *prototypes.SetMessageRequest) (*prototypes.SetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMessage not implemented")
}
func (UnimplementedPartitionServiceServer) GetMessage(context.Context, *prototypes.GetMessageRequest) (*prototypes.GetMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessage not implemented")
}
func (UnimplementedPartitionServiceServer) DeleteMessage(context.Context, *prototypes.DeleteMessageRequest) (*prototypes.DeleteMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMessage not implemented")
}
func (UnimplementedPartitionServiceServer) SetHashrange(context.Context, *prototypes.SetHashrangeRequest) (*prototypes.SetHashrangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHashrange not implemented")
}
func (UnimplementedPartitionServiceServer) mustEmbedUnimplementedPartitionServiceServer() {}

// UnsafePartitionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartitionServiceServer will
// result in compilation errors.
type UnsafePartitionServiceServer interface {
	mustEmbedUnimplementedPartitionServiceServer()
}

func RegisterPartitionServiceServer(s grpc.ServiceRegistrar, srv PartitionServiceServer) {
	s.RegisterService(&PartitionService_ServiceDesc, srv)
}

func _PartitionService_SetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(prototypes.SetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServiceServer).SetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkvs.partition.PartitionService/SetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServiceServer).SetMessage(ctx, req.(*prototypes.SetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionService_GetMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(prototypes.GetMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServiceServer).GetMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkvs.partition.PartitionService/GetMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServiceServer).GetMessage(ctx, req.(*prototypes.GetMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionService_DeleteMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(prototypes.DeleteMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServiceServer).DeleteMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkvs.partition.PartitionService/DeleteMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServiceServer).DeleteMessage(ctx, req.(*prototypes.DeleteMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartitionService_SetHashrange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(prototypes.SetHashrangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartitionServiceServer).SetHashrange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dkvs.partition.PartitionService/SetHashrange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartitionServiceServer).SetHashrange(ctx, req.(*prototypes.SetHashrangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartitionService_ServiceDesc is the grpc.ServiceDesc for PartitionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartitionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dkvs.partition.PartitionService",
	HandlerType: (*PartitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetMessage",
			Handler:    _PartitionService_SetMessage_Handler,
		},
		{
			MethodName: "GetMessage",
			Handler:    _PartitionService_GetMessage_Handler,
		},
		{
			MethodName: "DeleteMessage",
			Handler:    _PartitionService_DeleteMessage_Handler,
		},
		{
			MethodName: "SetHashrange",
			Handler:    _PartitionService_SetHashrange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dkvs/partition/rpc.proto",
}
