// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.9
// source: dkvs/message/message.proto

package prototypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StoreMessage is a message that is sent to a node that should store a key
type StoreMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StoreMessage) Reset() {
	*x = StoreMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dkvs_message_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMessage) ProtoMessage() {}

func (x *StoreMessage) ProtoReflect() protoreflect.Message {
	mi := &file_dkvs_message_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMessage.ProtoReflect.Descriptor instead.
func (*StoreMessage) Descriptor() ([]byte, []int) {
	return file_dkvs_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *StoreMessage) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreMessage) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_dkvs_message_message_proto protoreflect.FileDescriptor

var file_dkvs_message_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x6b, 0x76, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x64, 0x6b,
	0x76, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x79, 0x73, 0x65, 0x6c, 0x2f, 0x64, 0x6b, 0x76, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dkvs_message_message_proto_rawDescOnce sync.Once
	file_dkvs_message_message_proto_rawDescData = file_dkvs_message_message_proto_rawDesc
)

func file_dkvs_message_message_proto_rawDescGZIP() []byte {
	file_dkvs_message_message_proto_rawDescOnce.Do(func() {
		file_dkvs_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_dkvs_message_message_proto_rawDescData)
	})
	return file_dkvs_message_message_proto_rawDescData
}

var file_dkvs_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dkvs_message_message_proto_goTypes = []interface{}{
	(*StoreMessage)(nil), // 0: dkvs.message.StoreMessage
}
var file_dkvs_message_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dkvs_message_message_proto_init() }
func file_dkvs_message_message_proto_init() {
	if File_dkvs_message_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dkvs_message_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StoreMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dkvs_message_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dkvs_message_message_proto_goTypes,
		DependencyIndexes: file_dkvs_message_message_proto_depIdxs,
		MessageInfos:      file_dkvs_message_message_proto_msgTypes,
	}.Build()
	File_dkvs_message_message_proto = out.File
	file_dkvs_message_message_proto_rawDesc = nil
	file_dkvs_message_message_proto_goTypes = nil
	file_dkvs_message_message_proto_depIdxs = nil
}
